version: '3.8'
services:

  postgresql:
    container_name: postgreleague
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: league
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmileague
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"